apiVersion: v2
name: otus-product-chart
description: A Helm chart for Kubernetes

type: application

version: 0.0.7

appVersion: 1.16.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - product-database
  - name: redis
    version: 10.7.11
    repository: https://charts.bitnami.com/bitnami
    condition: resid.enabled
    tags:
      - product-redis