# Default values for otus-auth-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

fullnameOverride: "otus-product"

image: jawello/otus-product:0.0.7

data_generation:
  enabled: true
  image: jawello/otus-product-data-generator:0.0.7
  products_count: 100000
  loglevel: WARNING

service:
  type: NodePort
  port: 7000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - /products
        - /products_search

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: otus
  postgresqlDatabase: postgres
  service:
    port: "5432"

redis:
  enabled: true
  usePassword: false
  redisPort: "6379"
  cluster:
    enabled: false