app:
  loglevel: DEBUG
  port: 8080
database:
  DB_NAME: 'postgres'
  DB_USER: 'postgres'
  DB_PASS: 'otus'
  DB_HOST: 'postgres-product'
  DB_PORT: 5432
#redis:
#  REDIS_HOST: 'redis-auth'
#  REDIS_PORT: 6379