version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=otus
    restart: on-failure
  init_db:
    build:
      context: init_db
    volumes:
      - ${PWD}/config/alembic.ini:/migration/alembic.ini
    networks:
      - app
    depends_on:
      - postgres
    restart: on-failure
  otus_app:
    build:
      context: .
    volumes:
      - ${PWD}/config/otus.yaml:/app/config/otus.yaml
    networks:
      - app
    depends_on:
      - init_db
    restart: on-failure
networks:
  app:
