apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: otus-docker
build:
  artifacts:
  - image: otus-auth
    context: otus-auth/src
deploy:
  helm:
    releases:
      - name: otus-auth
        chartPath: otus-auth/otus-auth-chart
        artifactOverrides:
          image: otus-auth
        valuesFiles:
          - otus-auth/otus-auth-chart/values.yaml