apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: otus-docker
build:
  artifacts:
  - image: locust-stresstest
    context: stresstest/src
deploy:
  helm:
    releases:
      - name: locust-chart
        chartPath: stresstest/stresstest-chart
        artifactOverrides:
          image: locust-stresstest
        valuesFiles:
          - stresstest/stresstest-chart/values.yaml