version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=skytrack
    restart: on-failure
    logging:
      driver: none
  init_db:
    build:
      context: alembic
    volumes:
      - ${PWD}/config/alembic.ini:/migration/alembic.ini
    networks:
      - app
    depends_on:
      - postgres
    restart: on-failure
networks:
  app:
