version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=otus
    restart: on-failure
  otus_app:
    build:
      context: ""
    volumes:
      - ${PWD}/config:/app/config
    ports:
      - "8080:8000"
    networks:
      - app
    depends_on:
      - postgres
    restart: on-failure
    entrypoint: ["python", "main.py", "-c", "/app/config/otus.yaml", "-cm", "/app/config/alembic.ini"]
networks:
  app:
