# Default values for otus-auth-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: jawello/otus-auth:0.0.5

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        path: /otus-auth($|/)(.*)

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: otus
  postgresqlDatabase: postgres
  service:
    port: "5432"

redis:
  enabled: true
  usePassword: false
  redisPort: 6379