apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
        - name: otus
          image: jawello/otus:0.0.3
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: otus-app-config-volume
              mountPath: /app/config
      volumes:
        - name: otus-app-config-volume
          configMap:
            name: otus-app-config