name: Docker Push
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref##*/ }}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus_docker
          TAG_NAME: ${{ github.ref##*/ }}
          LATEST: "true"