name: Docker Push
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
          id: tag
          uses: actions/github-script@0.2.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Echo
        run: echo ${{ steps.tag.outputs.result }}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus_docker
          TAG_NAME: ${{ steps.tag.outputs.result }}
          LATEST: "true"