name: Docker Push Tag v
on:
  push:
    tags:
      - v*
jobs:
  docker-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION_OTUS_APP::${GITHUB_REF#*v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          BUILD_PATH: "otus-app/src"
          DOCKERFILE: "otus-app/src/Dockerfile"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus
          TAG_NAME: ${{ steps.get_version.outputs.VERSION_OTUS_APP }}
          LATEST: "true"
  stresstest-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION_OTUS_APP::${GITHUB_REF#*v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          BUILD_PATH: "stresstest/src"
          DOCKERFILE: "stresstest/src/Dockerfile"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/locust
          TAG_NAME: ${{ steps.get_version.outputs.VERSION_OTUS_APP }}
          LATEST: "true"
  auth-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION_OTUS_APP::${GITHUB_REF#*v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          BUILD_PATH: "otus-auth/src"
          DOCKERFILE: "otus-auth/src/Dockerfile"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus-auth
          TAG_NAME: ${{ steps.get_version.outputs.VERSION_OTUS_APP }}
          LATEST: "true"
  product-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION_OTUS_APP::${GITHUB_REF#*v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          BUILD_PATH: "otus-product/src"
          DOCKERFILE: "otus-product/src/Dockerfile"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus-product
          TAG_NAME: ${{ steps.get_version.outputs.VERSION_OTUS_APP }}
          LATEST: "true"
  product-data-generator-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION_OTUS_APP::${GITHUB_REF#*v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          BUILD_PATH: "otus-product/src"
          DOCKERFILE: "otus-product/src/Dockerfile_data_generator"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus-product-data-generator-app
          TAG_NAME: ${{ steps.get_version.outputs.VERSION_OTUS_APP }}
          LATEST: "true"