name: Docker Push
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#*v}
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        working-directory: otus-app
        with:
          args: --docker
        env:
          BUILD_PATH: "otus-app"
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/otus
          TAG_NAME: ${{ steps.get_version.outputs.VERSION }}
          LATEST: "true"
